myapp/urls.py
from django.conf.urls import url
from .views import FoodListView

urlpatterns = [
    url(r'^$', FoodListView.as_view(), name='list'),
]

myproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^mysite/', include('myapp.urls', namespace='my')),
]

myapp/models.py
from django.db import models

class Kind(models.Model):
    name = models.CharField('Name', max_length=255)

class Food(models.Model):
    kind = models.ForeignKey(Kind, verbose_name="品種")
    name = models.CharField('名前', max_length=255)

myapp/views.py
from django.views.generic import ListView
from .models import Kind, Food


class FoodListView(ListView):
    model = Food
    paginate_by = 2

    def get_context_data(self, **kwargs):
        context = super(FoodListView, self).get_context_data(**kwargs)

        # 絞り込み条件の設定
        kinds = Kind.objects.all()
        context['kinds'] = kinds
        
        return context
        
        
    def get_queryset(self):
        # デフォルトは全件取得
        results = self.model.objects.all()

        # GETのURLクエリパラメータを取得する
        # 該当のクエリパラメータが存在しない場合は、[]が返ってくる
        q_kinds = self.request.GET.getlist('kind')
        q_name = self.request.GET.get('name')

        # 品種での絞込は、Kind.pkとして存在してる値のみ対象とする
        # "a"とかを指定するとValueErrorになるため
        if len(q_kinds) != 0:
            kinds = [x for x in q_kinds if x in ["1", "2"]]
            results = results.filter(kind__in=kinds)
        
        # 名前での絞り込み
        if q_name is not None:
            results = results.filter(name__contains=q_name)
            
        return results

myapp/templates/myapp/food_list.html
{% load custom_filters %}
{% load custom_tags %}

<!DOCTYPE html>
<html lang="ja" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title>My Site</title>
    {% load staticfiles %}
    <link href={% static 'myapp/css/pagination.css' %} rel='stylesheet'>
</head>
<body>
    <form method="get" action="" name="filter_form">
        <legend>絞り込み条件</legend>
        <div>
            <span>種類：</span>
            {% for kind in kinds %}
                <input type="checkbox" id="filter_kind_{{ kind.pk }}" 
                    name="kind" 
                    value="{{ kind.pk }}"
                    {{ kind.pk|checked:request.GET }}
                    >{{ kind.name }}
            {% endfor %}
        </div>
        <div>
            <span>品種：</span>
            <input type="search" id="filter_name"
                name="name" 
                placeholder="品種名"
                value={{ request.GET|name }}>
            <button id="filter">絞り込み</button>
        </div>
    </form>

    <hr style="width: 100%; color: white; height: 1px; background-color:white;" />

    <div id="main">
        <h1>結果</h1>
        <table>
            <tr>
                <th>種類</th>
                <th>品種</th>
            </tr>
            {% for food in object_list %}
                <tr>
                    <td>{{ food.kind.name }}</td>
                    <td>{{ food.name }}</td>
                </tr>
            {% endfor %}
        </table>
    </div>
    
    {% if is_paginated %}
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li><a href="{% url 'my:list' %}?{% query_string request page_obj.previous_page_number %}">previous</a></li>
            {% endif %}
            {% for link_page in page_obj.paginator.page_range %}
                {% if link_page == page_obj.number %}
                    <li class="active">{{ link_page }}</li>
                {% else %}
                    <li><a href="{% url 'my:list' %}?{% query_string request link_page %}">{{ link_page }}</a></li>
                {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
                <li><a href="{% url 'my:list' %}?{% query_string request page_obj.next_page_number %}">next</a></li>
            {% endif %}
        </ul>
    {% endif %}
</body>
</html>